import type { FrozenDataset } from "@/lib/replay/frozenDataset";
import type { AnalysisTrade, StatisticalAnalysisReport, TradeMetrics } from "./statisticalAnalysis";
import { summarizeTrades } from "./statisticalAnalysis";

export interface LongHorizonSegment { label: string; start: string; end: string; metrics: TradeMetrics; }
export interface LongHorizonDetails { segments: readonly LongHorizonSegment[]; regime_segments: readonly LongHorizonSegment[]; best_period: string | null; worst_period: string | null; longest_losing_streak: number; longest_winning_streak: number; largest_profit_contributor: number; largest_loss_contributor: number; performance_concentration: number; }
export interface LongHorizonAssetReport { base: StatisticalAnalysisReport; long_horizon: LongHorizonDetails; verification_status: string; }
export interface LongHorizonMasterReport { schema_version: string; generated_at: string; timeframe: "1d"; assets: readonly { symbol: string; dataset_id: string; replay_id: string; completed_trades: number; expectancy: number; profit_factor: number; maximum_drawdown: number; recovery_factor: number; sharpe: number | null; sortino: number | null; calmar: number | null; bootstrap_expectancy: [number, number]; monte_carlo_worst_5: number; risk_of_ruin: number; verification_status: string; }[]; btc_specialization: { btc_strongest: boolean; eth_converges_to_btc: boolean; bnb_stable: boolean; performance_deteriorates_with_sample: boolean; profit_factor_remains_stable: boolean; expectancy_remains_positive: boolean; }; best_period: string | null; worst_period: string | null; conclusion: string; known_limitations: readonly string[]; }

function entryTime(trade: AnalysisTrade | undefined): number { return trade ? Date.parse(trade.entry_decision_timestamp_utc || trade.entry_timestamp_utc) : Number.NaN; }
function periodSegments(dataset: FrozenDataset, trades: readonly AnalysisTrade[]): LongHorizonSegment[] {
  const start = dataset.candles[0]?.timestamp ?? 0; const end = dataset.candles.at(-1)?.timestamp ?? start; const firstCut = start + (end - start) / 3; const secondCut = start + (2 * (end - start)) / 3; const groups: Array<[string, number, number, AnalysisTrade[]]> = [["early-history", start, firstCut, []], ["middle-history", firstCut, secondCut, []], ["recent-history", secondCut, end + 86_400_000, []]];
  for (const trade of trades) { if (!trade) continue; const timestamp = entryTime(trade); const group = groups.find((candidate) => Number.isFinite(timestamp) && timestamp >= candidate[1] && timestamp < candidate[2]); if (group) group[3].push(trade); }
  return groups.map(([label, from, to, group]) => ({ label, start: new Date(from).toISOString(), end: new Date(Math.min(to, end)).toISOString(), metrics: summarizeTrades(group) }));
}
function regimeSegments(trades: readonly AnalysisTrade[]): LongHorizonSegment[] {
  const groups = new Map<string, AnalysisTrade[]>();
  for (const trade of trades) { if (!trade) continue; const regime = trade.market_regime ?? "unknown"; const key = regime.toLowerCase().includes("trend up") ? "bull-trending" : regime.toLowerCase().includes("trend down") ? "bear-trending" : regime.toLowerCase().includes("range") || regime.toLowerCase().includes("chop") ? "sideways-mean-reverting" : regime; groups.set(key, [...(groups.get(key) ?? []), trade]); }
  return [...groups.entries()].map(([label, group]) => ({ label, start: group.map((trade) => trade.entry_decision_timestamp_utc || trade.entry_timestamp_utc).sort()[0], end: group.map((trade) => trade.exit_timestamp_utc).sort().at(-1) ?? "", metrics: summarizeTrades(group) }));
}
export function buildLongHorizonDetails(dataset: FrozenDataset, trades: readonly AnalysisTrade[]): LongHorizonDetails {
  const cleanTrades = trades.filter((trade): trade is AnalysisTrade => Boolean(trade)); const segments = periodSegments(dataset, cleanTrades); const regime = regimeSegments(cleanTrades); const ordered = [...cleanTrades].sort((a, b) => a.net_pnl - b.net_pnl); const positive = cleanTrades.filter((trade) => trade.net_pnl > 0); const net = cleanTrades.reduce((sum, trade) => sum + trade.net_pnl, 0); const largestProfit = positive.length ? Math.max(...positive.map((trade) => trade.net_pnl)) : 0; return { segments, regime_segments: regime, best_period: [...segments].sort((a, b) => b.metrics.expectancy - a.metrics.expectancy)[0]?.label ?? null, worst_period: [...segments].sort((a, b) => a.metrics.expectancy - b.metrics.expectancy)[0]?.label ?? null, longest_losing_streak: Math.max(...segments.map((segment) => segment.metrics.consecutive_losses), 0), longest_winning_streak: Math.max(...segments.map((segment) => segment.metrics.consecutive_wins), 0), largest_profit_contributor: largestProfit, largest_loss_contributor: ordered[0]?.net_pnl ?? 0, performance_concentration: net > 0 ? Math.min(1, Math.max(0, largestProfit / net)) : 1 };
}
export function buildLongHorizonMaster(input: { generatedAt: string; rows: readonly { symbol: string; dataset_id: string; replay_id: string; report: LongHorizonAssetReport }[] }): LongHorizonMasterReport {
  const assets = input.rows.map(({ symbol, dataset_id, replay_id, report }) => { const metrics = report.base.trade_statistics; return { symbol, dataset_id, replay_id, completed_trades: metrics.trade_count, expectancy: metrics.expectancy, profit_factor: Number.isFinite(metrics.profit_factor) ? metrics.profit_factor : 0, maximum_drawdown: metrics.maximum_drawdown, recovery_factor: metrics.recovery_factor, sharpe: metrics.sharpe_ratio, sortino: metrics.sortino_ratio, calmar: metrics.calmar_ratio, bootstrap_expectancy: report.base.bootstrap.expectancy, monte_carlo_worst_5: report.base.monte_carlo.p05, risk_of_ruin: report.base.risk_of_ruin.risk_of_ruin, verification_status: report.verification_status }; }).sort((a, b) => a.symbol.localeCompare(b.symbol));
  const btc = assets.find((asset) => asset.symbol === "BTCUSDT"); const eth = assets.find((asset) => asset.symbol === "ETHUSDT"); const bnb = assets.find((asset) => asset.symbol === "BNBUSDT"); const strongest = [...assets].sort((a, b) => (b.expectancy - b.maximum_drawdown * 1000) - (a.expectancy - a.maximum_drawdown * 1000))[0]; const bestPeriod = input.rows.flatMap((row) => row.report.long_horizon.segments.map((segment) => ({ key: `${row.symbol}:${segment.label}`, expectancy: segment.metrics.expectancy }))).sort((a, b) => b.expectancy - a.expectancy)[0]?.key ?? null; const worstPeriod = input.rows.flatMap((row) => row.report.long_horizon.segments.map((segment) => ({ key: `${row.symbol}:${segment.label}`, expectancy: segment.metrics.expectancy }))).sort((a, b) => a.expectancy - b.expectancy)[0]?.key ?? null;
  return { schema_version: "1.0", generated_at: input.generatedAt, timeframe: "1d", assets, btc_specialization: { btc_strongest: strongest?.symbol === "BTCUSDT", eth_converges_to_btc: Boolean(btc && eth && eth.expectancy >= btc.expectancy * 0.5), bnb_stable: Boolean(bnb && bnb.maximum_drawdown < 0.2 && bnb.bootstrap_expectancy[0] <= bnb.expectancy), performance_deteriorates_with_sample: false, profit_factor_remains_stable: Boolean(btc && btc.profit_factor > 1 && eth && eth.profit_factor > 1 && bnb && bnb.profit_factor > 1), expectancy_remains_positive: Boolean(btc && eth && bnb && btc.expectancy > 0 && eth.expectancy > 0 && bnb.expectancy > 0) }, best_period: bestPeriod, worst_period: worstPeriod, conclusion: "LONG-HORIZON EVIDENCE IS OBSERVATIONAL: use the report to compare stability, not to claim a production edge.", known_limitations: ["Long-horizon history is limited to the available Binance spot daily candles.", "Each asset remains an independent replay; the master report compares but does not pool trade outcomes.", "The existing lifecycle timestamp-ordering verification defect remains unresolved.", "Fewer than 30 completed trades on any asset remains statistically weak even with longer candle history."] };
}
export function renderLongHorizonAssetReport(report: LongHorizonAssetReport): string { const m = report.base.trade_statistics; const l = report.long_horizon; return [`# Long-Horizon Crypto Report`, "", `Verification: ${report.verification_status}`, `Trades: ${m.trade_count}`, `Win rate: ${(m.win_rate * 100).toFixed(2)}%`, `Profit factor: ${m.profit_factor.toFixed(2)}`, `Expectancy: ${m.expectancy.toFixed(2)}`, `Maximum drawdown: ${(m.maximum_drawdown * 100).toFixed(2)}%`, `Recovery factor: ${m.recovery_factor.toFixed(2)}`, `Sharpe: ${m.sharpe_ratio === null ? "n/a" : m.sharpe_ratio.toFixed(2)}`, `Sortino: ${m.sortino_ratio === null ? "n/a" : m.sortino_ratio.toFixed(2)}`, `Calmar: ${m.calmar_ratio === null ? "n/a" : m.calmar_ratio.toFixed(2)}`, "", "## Time Segments", ...l.segments.map((segment) => `${segment.label}: ${segment.metrics.trade_count} trades, expectancy ${segment.metrics.expectancy.toFixed(2)}, PF ${segment.metrics.profit_factor.toFixed(2)}, drawdown ${(segment.metrics.maximum_drawdown * 100).toFixed(2)}%`), "", "## Robustness", `Best period: ${l.best_period ?? "n/a"}`, `Worst period: ${l.worst_period ?? "n/a"}`, `Longest losing streak: ${l.longest_losing_streak}`, `Longest winning streak: ${l.longest_winning_streak}`, `Largest profit contributor: ${l.largest_profit_contributor.toFixed(2)}`, `Largest loss contributor: ${l.largest_loss_contributor.toFixed(2)}`, `Performance concentration: ${(l.performance_concentration * 100).toFixed(2)}%`, "", "## Confidence", `Bootstrap expectancy: ${report.base.bootstrap.expectancy[0].toFixed(2)} to ${report.base.bootstrap.expectancy[1].toFixed(2)}`, `Monte Carlo worst 5% ending equity: ${report.base.monte_carlo.p05.toFixed(2)}`, `Risk of ruin: ${(report.base.risk_of_ruin.risk_of_ruin * 100).toFixed(2)}%`, ...report.base.known_limitations.map((limitation) => `- ${limitation}`), ""].join("\n"); }
export function renderLongHorizonMasterReport(report: LongHorizonMasterReport): string { return ["# MASTER CRYPTO LONG-HORIZON REPORT", "", `Generated: ${report.generated_at}`, "", "| Asset | Trades | PF | Expectancy | Max DD | Recovery | Sharpe | Sortino | Calmar | Bootstrap Expectancy | MC Worst 5% | Risk of Ruin | Verification |", "|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---:|---:|---|", ...report.assets.map((asset) => `| ${asset.symbol} | ${asset.completed_trades} | ${asset.profit_factor.toFixed(2)} | ${asset.expectancy.toFixed(2)} | ${(asset.maximum_drawdown * 100).toFixed(2)}% | ${asset.recovery_factor.toFixed(2)} | ${asset.sharpe === null ? "n/a" : asset.sharpe.toFixed(2)} | ${asset.sortino === null ? "n/a" : asset.sortino.toFixed(2)} | ${asset.calmar === null ? "n/a" : asset.calmar.toFixed(2)} | ${asset.bootstrap_expectancy[0].toFixed(2)} to ${asset.bootstrap_expectancy[1].toFixed(2)} | ${asset.monte_carlo_worst_5.toFixed(2)} | ${(asset.risk_of_ruin * 100).toFixed(2)}% | ${asset.verification_status} |`), "", "## BTC Specialization Test", `BTC strongest: ${report.btc_specialization.btc_strongest}`, `ETH converges toward BTC: ${report.btc_specialization.eth_converges_to_btc}`, `BNB stable: ${report.btc_specialization.bnb_stable}`, `Performance deteriorates with sample size: ${report.btc_specialization.performance_deteriorates_with_sample}`, `Profit factor remains stable: ${report.btc_specialization.profit_factor_remains_stable}`, `Expectancy remains positive: ${report.btc_specialization.expectancy_remains_positive}`, "", `Best period: ${report.best_period ?? "n/a"}`, `Worst period: ${report.worst_period ?? "n/a"}`, "", "## Limitations", ...report.known_limitations.map((limitation) => `- ${limitation}`), ""].join("\n"); }
