import type { ExecutionEvent } from "@/lib/trading/executionEvent";
import type { LifecycleEvent } from "@/lib/trading/lifecycleEvent";
import type { TradeRecord } from "@/lib/trading/tradeJournal";
import type { StrategyTraceRecord } from "@/lib/replay/strategyTrace";

export const PROPOSAL_STAGES = ["signal", "evidence", "risk", "expected value", "Kelly", "proposal", "order creation", "execution", "completed trade"] as const;
export type ProposalStage = typeof PROPOSAL_STAGES[number];

export interface ProposalStageResult { stage: ProposalStage; entered: boolean; passed: boolean; rejected: boolean; reason: string | null; source: "trace" | "lifecycle" | "execution" | "trade" | "not emitted"; }
export interface ProposalAuditRecord { proposal_id: string; timestamp: string; trace_status: string | null; trace_stage: string | null; lifecycle_states: readonly string[]; stages: readonly ProposalStageResult[]; first_divergence: { stage: ProposalStage; trace: string; lifecycle: string } | null; terminal_state: string | null; terminal_reason: string | null; representative: boolean; }
export interface ProposalStageSummary { stage: ProposalStage; entering: number; passing: number; rejected: number; rejection_percentage: number; top_rejection_reasons: readonly { reason: string; count: number }[]; representative_examples: readonly { proposal_id: string; timestamp: string; reason: string }[]; }
export interface ProposalFunnelAuditReport { schema_version: string; replay_id: string; dataset_id: string; symbol: string; generated_at: string; proposal_count: number; stage_summaries: readonly ProposalStageSummary[]; proposals: readonly ProposalAuditRecord[]; waterfall: readonly { stage: string; count: number; retained_percentage: number; reduction: number }[]; greatest_reduction_stage: ProposalStage; greatest_reduction_count: number; mismatch_count: number; mismatches: readonly { proposal_id: string; timestamp: string; first_divergence: ProposalStage; trace: string; lifecycle: string }[]; lifecycle_unemitted_stages: readonly ProposalStage[]; conclusion: string; }

function percent(value: number, total: number): number { return total ? Number((value / total * 100).toFixed(4)) : 0; }
function firstByTimestamp<T extends { timestamp_utc: string }>(values: readonly T[]): T | undefined { return [...values].sort((a, b) => Date.parse(a.timestamp_utc) - Date.parse(b.timestamp_utc))[0]; }
function lifecycleState(events: readonly LifecycleEvent[], state: string): boolean { return events.some((event) => event.state_after === state); }
function stageOrder(status: string | null, stage: ProposalStage): boolean { if (!status || status === "no signal") return false; const rank: Record<string, number> = { "signal rejected": 0, "evidence rejected": 1, "risk rejected": 2, "EV rejected": 3, "Kelly rejected": 4, "proposal created": 6, execution: 8, "completed trade": 9 }; const required: Record<ProposalStage, number> = { signal: 1, evidence: 2, risk: 3, "expected value": 4, Kelly: 5, proposal: 6, "order creation": 7, execution: 8, "completed trade": 9 }; return (rank[status] ?? -1) >= required[stage]; }
function result(stage: ProposalStage, entered: boolean, passed: boolean, source: ProposalStageResult["source"], reason: string | null = null): ProposalStageResult { return { stage, entered, passed, rejected: entered && !passed, reason, source }; }

function proposalRecord(proposalId: string, events: readonly LifecycleEvent[], trace: StrategyTraceRecord | undefined, executions: readonly ExecutionEvent[], trades: readonly TradeRecord[]): ProposalAuditRecord {
  const ordered = [...events].sort((a, b) => a.lifecycle_sequence - b.lifecycle_sequence); const proposal = ordered.find((event) => event.state_after === "TRADE_PROPOSED") ?? ordered[0]; const timestamp = proposal?.timestamp_utc ?? trace?.timestamp ?? ""; const terminal = ordered.find((event) => event.state_after === "TRADE_REJECTED" || event.state_after === "TRADE_COMPLETED"); const reason = terminal?.reason ?? null; const signal = lifecycleState(ordered, "SIGNAL_GENERATED"); const evidence = lifecycleState(ordered, "RISK_VALIDATED"); const risk = evidence; const ev = lifecycleState(ordered, "ORDER_CREATED"); const kelly = ev; const created = lifecycleState(ordered, "TRADE_PROPOSED"); const order = lifecycleState(ordered, "ORDER_CREATED"); const execution = executions.some((event) => event.trade_id === proposalId && event.filled_quantity > 0); const completed = trades.some((trade) => trade.trade_id === proposalId) || lifecycleState(ordered, "TRADE_COMPLETED"); const lifecycleResults = [result("signal", true, signal, "lifecycle", signal ? null : reason), result("evidence", signal, evidence, evidence ? "lifecycle" : "not emitted", evidence ? null : reason), result("risk", evidence, risk, risk ? "lifecycle" : "not emitted", risk ? null : reason), result("expected value", risk, ev, ev ? "lifecycle" : "not emitted", ev ? null : reason), result("Kelly", ev, kelly, kelly ? "lifecycle" : "not emitted", kelly ? null : reason), result("proposal", true, created, "lifecycle", created ? null : reason), result("order creation", created, order, order ? "lifecycle" : "not emitted", order ? null : reason), result("execution", order, execution, execution ? "execution" : "not emitted", execution ? null : reason), result("completed trade", execution, completed, completed ? "trade" : "not emitted", completed ? null : reason)];
  const traceStatus = trace?.final_status ?? null; const traceResults = PROPOSAL_STAGES.map((stage) => result(stage, lifecycleResults.find((item) => item.stage === stage)?.entered ?? false, stageOrder(traceStatus, stage), "trace", stageOrder(traceStatus, stage) ? null : trace?.rejection_reason ?? null)); const divergence = PROPOSAL_STAGES.map((stage, index) => ({ stage, trace: traceResults[index].passed ? "pass" : "reject", lifecycle: lifecycleResults[index].passed ? "pass" : "reject" })).find((item) => item.trace !== item.lifecycle); return { proposal_id: proposalId, timestamp, trace_status: traceStatus, trace_stage: trace?.pipeline_stage_reached ?? null, lifecycle_states: ordered.map((event) => event.state_after), stages: lifecycleResults, first_divergence: divergence ? { stage: divergence.stage, trace: divergence.trace, lifecycle: divergence.lifecycle } : null, terminal_state: terminal?.state_after ?? null, terminal_reason: reason, representative: false };
}

function summarize(stage: ProposalStage, proposals: readonly ProposalAuditRecord[]): ProposalStageSummary { const current = proposals.map((proposal) => ({ proposal, stage: proposal.stages.find((item) => item.stage === stage)! })).filter((item) => item.stage.entered); const rejected = current.filter((item) => item.stage.rejected); const reasons = new Map<string, number>(); for (const item of rejected) { const reason = item.stage.reason ?? "unspecified"; reasons.set(reason, (reasons.get(reason) ?? 0) + 1); } const examples = rejected.slice(0, 3).map((item) => ({ proposal_id: item.proposal.proposal_id, timestamp: item.proposal.timestamp, reason: item.stage.reason ?? "unspecified" })); return { stage, entering: current.length, passing: current.filter((item) => item.stage.passed).length, rejected: rejected.length, rejection_percentage: percent(rejected.length, current.length), top_rejection_reasons: [...reasons.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([reason, count]) => ({ reason, count })), representative_examples: examples }; }

export function buildProposalFunnelAudit(input: { replayId: string; datasetId: string; symbol: string; generatedAt: string; proposals: readonly { proposal_id: string; lifecycle: readonly LifecycleEvent[] }[]; traces: readonly StrategyTraceRecord[]; executions: readonly ExecutionEvent[]; trades: readonly TradeRecord[] }): ProposalFunnelAuditReport { const traceByTimestamp = new Map(input.traces.map((trace) => [trace.timestamp, trace])); const records = input.proposals.map(({ proposal_id, lifecycle }) => { const proposal = lifecycle.find((event) => event.state_after === "TRADE_PROPOSED"); return proposalRecord(proposal_id, lifecycle, proposal ? traceByTimestamp.get(proposal.timestamp_utc) : undefined, input.executions, input.trades); }); const summaries = PROPOSAL_STAGES.map((stage) => summarize(stage, records)); const counts: Array<[string, number]> = [["proposals", records.length], ...summaries.map((summary) => [summary.stage, summary.passing] as [string, number])]; const waterfall = counts.map(([stage, count], index) => ({ stage, count, retained_percentage: percent(count, records.length), reduction: index ? counts[index - 1][1] - count : 0 })); const reductions = summaries.map((summary, index) => ({ stage: summary.stage, reduction: index ? counts[index][1] - counts[index + 1][1] : records.length - summary.passing })); const greatest = [...reductions].sort((a, b) => b.reduction - a.reduction)[0] ?? { stage: "risk" as ProposalStage, reduction: 0 }; const mismatches = records.filter((record) => record.first_divergence).map((record) => ({ proposal_id: record.proposal_id, timestamp: record.timestamp, first_divergence: record.first_divergence!.stage, trace: record.first_divergence!.trace, lifecycle: record.first_divergence!.lifecycle })); const lifecycleUnemitted: ProposalStage[] = ["evidence", "expected value", "Kelly"].filter((stage) => records.some((record) => record.stages.find((item) => item.stage === stage)?.source === "not emitted")) as ProposalStage[]; return { schema_version: "1.0", replay_id: input.replayId, dataset_id: input.datasetId, symbol: input.symbol, generated_at: input.generatedAt, proposal_count: records.length, stage_summaries: summaries, proposals: records.map((record, index) => ({ ...record, representative: mismatches.slice(0, 3).some((item) => item.proposal_id === record.proposal_id) || index < 3 })), waterfall, greatest_reduction_stage: greatest.stage, greatest_reduction_count: greatest.reduction, mismatch_count: mismatches.length, mismatches, lifecycle_unemitted_stages: lifecycleUnemitted, conclusion: `The greatest observed reduction is at ${greatest.stage} (${greatest.reduction} proposals). ${mismatches.length} of ${records.length} proposals diverge between trace and lifecycle stage outcomes.` }; }

export function renderProposalFunnelAudit(report: ProposalFunnelAuditReport): string { const summaries = report.stage_summaries.map((summary) => [`### ${summary.stage}`, `Entering: ${summary.entering}`, `Passing: ${summary.passing}`, `Rejected: ${summary.rejected}`, `Rejected percentage: ${summary.rejection_percentage.toFixed(2)}%`, "Top reasons:", ...summary.top_rejection_reasons.map((item) => `- ${item.count}x ${item.reason}`), "Representative examples:", ...summary.representative_examples.map((item) => `- ${item.proposal_id} at ${item.timestamp}: ${item.reason}`), ""].join("\n")).join("\n"); const waterfall = report.waterfall.map((row) => `| ${row.stage} | ${row.count} | ${row.retained_percentage.toFixed(2)}% | ${row.reduction} |`).join("\n"); const mismatches = report.mismatches.slice(0, 100).map((item) => `| ${item.proposal_id} | ${item.timestamp} | ${item.first_divergence} | ${item.trace} | ${item.lifecycle} |`).join("\n"); return [`# ${report.symbol} Proposal Funnel Audit`, "", `Replay: ${report.replay_id}`, `Proposals: ${report.proposal_count}`, "", "## Stage Funnel", summaries, "## Waterfall", "| Stage | Count | Retained | Reduction |", "|---|---:|---:|---:|", waterfall, "", `Greatest reduction: **${report.greatest_reduction_stage} (${report.greatest_reduction_count})**`, "", "## Trace/Lifecycle Mismatches", `Mismatch count: ${report.mismatch_count}`, "| Proposal ID | Timestamp | First divergence | Trace | Lifecycle |", "|---|---|---|---|---|", mismatches || "| None | | | | |", "", `Lifecycle stages not separately emitted: ${report.lifecycle_unemitted_stages.join(", ") || "none"}`, "", "## Conclusion", report.conclusion, ""].join("\n"); }
