import type { TradeRecord } from "@/lib/trading/tradeJournal";

export type AnalysisTrade = Pick<TradeRecord, "net_pnl" | "return_percent" | "r_multiple" | "entry_timestamp_utc" | "exit_timestamp_utc" | "data_snapshot_id" | "instrument" | "market_regime" | "volatility_regime"> & Partial<Pick<TradeRecord, "entry_decision_timestamp_utc" | "notional_value" | "quantity" | "direction" | "risk_percent" | "liquidity_regime">>;

export interface TradeMetrics {
  trade_count: number; winning_trades: number; losing_trades: number; win_rate: number; loss_rate: number;
  average_win: number; average_loss: number; largest_win: number; largest_loss: number; average_holding_days: number; trade_frequency_per_year: number;
  gross_profit: number; gross_loss: number; net_profit: number; expectancy: number; expected_value_per_trade: number; payoff_ratio: number; profit_factor: number; recovery_factor: number; edge_ratio: number; average_r_multiple: number; r_multiple_distribution: number[];
  maximum_drawdown: number; maximum_equity_drawdown: number; average_drawdown: number; longest_drawdown_days: number; consecutive_wins: number; consecutive_losses: number; exposure: number; capital_utilization: number; time_under_water: number;
  cagr: number | null; annualized_return: number | null; volatility: number | null; sharpe_ratio: number | null; sortino_ratio: number | null; calmar_ratio: number | null; mar_ratio: number | null; ulcer_index: number | null;
}

export interface DistributionSummary { median: number; p05: number; p95: number; maximum_drawdown: number; ending_equity: number[]; simulations: number; seed: number; }
export interface BootstrapSummary { samples: number; seed: number; confidence_level: number; expectancy: [number, number]; profit_factor: [number, number]; win_rate: [number, number]; average_return: [number, number]; }
export interface RiskOfRuinSummary { risk_of_ruin: number; probability_drawdown_20: number; probability_drawdown_30: number; probability_equity_doubling: number; probability_new_equity_high: number; simulations: number; }
export interface RegimeSummary { dimension: string; key: string; trade_count: number; net_profit: number; win_rate: number; expectancy: number; profit_factor: number; }
export interface WalkForwardRow { start: string; end: string; trade_count: number; expectancy: number; sharpe: number | null; drawdown: number; }
export interface StatisticalAnalysisReport { schema_version: string; generated_at: string; replay_ids: string[]; capital: number; executive_summary: string; dataset_summary: unknown[]; trade_statistics: TradeMetrics; monte_carlo: DistributionSummary; bootstrap: BootstrapSummary; risk_of_ruin: RiskOfRuinSummary; regime_analysis: RegimeSummary[]; out_of_sample: { training: TradeMetrics; validation: TradeMetrics; out_of_sample: TradeMetrics }; walk_forward: WalkForwardRow[]; robustness: Record<string, number | string | boolean>; known_limitations: string[]; conclusion: string; }

function mean(values: readonly number[]): number { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; }
function sum(values: readonly number[]): number { return values.reduce((total, value) => total + value, 0); }
function variance(values: readonly number[]): number { if (values.length < 2) return 0; const average = mean(values); return mean(values.map((value) => (value - average) ** 2)); }
function stdev(values: readonly number[]): number { return Math.sqrt(variance(values)); }
function quantile(values: readonly number[], probability: number): number { if (!values.length) return 0; const ordered = [...values].sort((a, b) => a - b); const position = (ordered.length - 1) * probability; const lower = Math.floor(position); const upper = Math.ceil(position); return ordered[lower] + (ordered[upper] - ordered[lower]) * (position - lower); }
function daysBetween(start: string, end: string): number { return Math.max(0, (Date.parse(end) - Date.parse(start)) / 86_400_000); }
function entryTime(trade: AnalysisTrade): string { return trade.entry_decision_timestamp_utc || trade.entry_timestamp_utc; }
function longestRun(values: readonly boolean[], target: boolean): number { let current = 0; let longest = 0; for (const value of values) { current = value === target ? current + 1 : 0; longest = Math.max(longest, current); } return longest; }
function equityCurve(trades: readonly AnalysisTrade[], capital: number): number[] { let equity = capital; const curve = [equity]; for (const trade of trades) { equity += trade.net_pnl; curve.push(equity); } return curve; }
function drawdownStats(curve: readonly number[], timestamps: readonly string[]): { maximum: number; average: number; longestDays: number; timeUnderWater: number; ulcer: number } {
  let peak = curve[0] ?? 0; let maximum = 0; let peakIndex = 0; let longestDays = 0; let underwater = 0; const drawdowns: number[] = [];
  for (let index = 0; index < curve.length; index += 1) { const value = curve[index]; if (value >= peak) { peak = value; peakIndex = index; } const drawdown = peak > 0 ? (peak - value) / peak : 0; drawdowns.push(drawdown); if (drawdown > 0) underwater += 1; if (drawdown > maximum) { maximum = drawdown; longestDays = timestamps.length > index && timestamps.length > peakIndex ? daysBetween(timestamps[peakIndex], timestamps[index]) : 0; } }
  return { maximum, average: mean(drawdowns), longestDays, timeUnderWater: curve.length ? underwater / curve.length : 0, ulcer: Math.sqrt(mean(drawdowns.map((value) => value ** 2))) };
}

export function summarizeTrades(trades: readonly AnalysisTrade[], capital = 100_000): TradeMetrics {
  if (!trades.length) return { trade_count: 0, winning_trades: 0, losing_trades: 0, win_rate: 0, loss_rate: 0, average_win: 0, average_loss: 0, largest_win: 0, largest_loss: 0, average_holding_days: 0, trade_frequency_per_year: 0, gross_profit: 0, gross_loss: 0, net_profit: 0, expectancy: 0, expected_value_per_trade: 0, payoff_ratio: 0, profit_factor: 0, recovery_factor: 0, edge_ratio: 0, average_r_multiple: 0, r_multiple_distribution: [], maximum_drawdown: 0, maximum_equity_drawdown: 0, average_drawdown: 0, longest_drawdown_days: 0, consecutive_wins: 0, consecutive_losses: 0, exposure: 0, capital_utilization: 0, time_under_water: 0, cagr: null, annualized_return: null, volatility: null, sharpe_ratio: null, sortino_ratio: null, calmar_ratio: null, mar_ratio: null, ulcer_index: 0 };
  const ordered = [...trades].sort((a, b) => Date.parse(a.exit_timestamp_utc) - Date.parse(b.exit_timestamp_utc));
  const profits = ordered.map((trade) => trade.net_pnl).filter((value) => value > 0); const losses = ordered.map((trade) => trade.net_pnl).filter((value) => value < 0); const returns = ordered.map((trade) => trade.return_percent); const rs = ordered.map((trade) => trade.r_multiple); const totalDays = ordered.length > 1 ? daysBetween(entryTime(ordered[0]), ordered.at(-1)!.exit_timestamp_utc) : 0; const curve = equityCurve(ordered, capital); const timestamps = [entryTime(ordered[0]) || new Date(0).toISOString(), ...ordered.map((trade) => trade.exit_timestamp_utc)]; const dd = drawdownStats(curve, timestamps); const grossProfit = sum(profits); const grossLoss = sum(losses); const netProfit = grossProfit + grossLoss; const holdingDays = ordered.map((trade) => daysBetween(entryTime(trade), trade.exit_timestamp_utc)); const averageTradeReturn = mean(returns); const annualFactor = totalDays > 0 ? 365 / totalDays : 0; const annualized = totalDays > 0 ? (capital + netProfit > 0 ? (capital + netProfit) / capital ** 1 : 1) ** annualFactor - 1 : null; const dailyized = totalDays > 0 ? returns.map((value) => value / Math.max(1, mean(holdingDays))) : [];
  const sharpe = dailyized.length > 1 && stdev(dailyized) > 0 ? mean(dailyized) / stdev(dailyized) * Math.sqrt(252) : null; const downside = stdev(dailyized.filter((value) => value < 0)); const sortino = dailyized.length > 1 && downside > 0 ? mean(dailyized) / downside * Math.sqrt(252) : null;
  const maxLoss = Math.abs(Math.min(...losses, 0)); const grossLossMagnitude = Math.abs(grossLoss); const maxWin = Math.max(...profits, 0); const maxDd = dd.maximum; const exposure = ordered.length ? mean(ordered.map((trade) => trade.notional_value ?? 0)) : 0;
  return { trade_count: ordered.length, winning_trades: profits.length, losing_trades: losses.length, win_rate: ordered.length ? profits.length / ordered.length : 0, loss_rate: ordered.length ? losses.length / ordered.length : 0, average_win: mean(profits), average_loss: mean(losses), largest_win: maxWin, largest_loss: -maxLoss, average_holding_days: mean(holdingDays), trade_frequency_per_year: totalDays > 0 ? ordered.length / (totalDays / 365) : 0, gross_profit: grossProfit, gross_loss: grossLoss, net_profit: netProfit, expectancy: ordered.length ? netProfit / ordered.length : 0, expected_value_per_trade: ordered.length ? netProfit / ordered.length : 0, payoff_ratio: maxLoss > 0 ? mean(profits) / maxLoss : 0, profit_factor: grossLossMagnitude > 0 ? grossProfit / grossLossMagnitude : grossProfit > 0 ? Infinity : 0, recovery_factor: maxDd > 0 ? netProfit / (maxDd * capital) : 0, edge_ratio: maxLoss > 0 ? mean(profits) / maxLoss : 0, average_r_multiple: mean(rs), r_multiple_distribution: rs, maximum_drawdown: maxDd, maximum_equity_drawdown: maxDd * capital, average_drawdown: dd.average, longest_drawdown_days: dd.longestDays, consecutive_wins: longestRun(ordered.map((trade) => trade.net_pnl > 0), true), consecutive_losses: longestRun(ordered.map((trade) => trade.net_pnl < 0), true), exposure, capital_utilization: capital > 0 ? exposure / capital : 0, time_under_water: dd.timeUnderWater, cagr: annualized, annualized_return: totalDays > 0 ? ((capital + netProfit) / capital) ** annualFactor - 1 : null, volatility: dailyized.length > 1 ? stdev(dailyized) * Math.sqrt(252) : null, sharpe_ratio: sharpe, sortino_ratio: sortino, calmar_ratio: maxDd > 0 && totalDays > 0 ? (((capital + netProfit) / capital) ** annualFactor - 1) / maxDd : null, mar_ratio: maxDd > 0 && totalDays > 0 ? (((capital + netProfit) / capital) ** annualFactor - 1) / maxDd : null, ulcer_index: dd.ulcer };
}

function rng(seed: number): () => number { let state = seed >>> 0; return () => { state = (1664525 * state + 1013904223) >>> 0; return state / 4_294_967_296; }; }
function shuffled<T>(items: readonly T[], random: () => number): T[] { const result = [...items]; for (let index = result.length - 1; index > 0; index -= 1) { const other = Math.floor(random() * (index + 1)); [result[index], result[other]] = [result[other], result[index]]; } return result; }

export function monteCarlo(trades: readonly AnalysisTrade[], simulations = 10_000, seed = 20250713, capital = 100_000): DistributionSummary {
  const random = rng(seed); const ending: number[] = []; let maximumDrawdown = 0;
  for (let simulation = 0; simulation < simulations; simulation += 1) { let equity = capital; let peak = capital; let drawdown = 0; for (const trade of shuffled(trades, random)) { equity += trade.net_pnl; peak = Math.max(peak, equity); drawdown = Math.max(drawdown, peak > 0 ? (peak - equity) / peak : 1); } ending.push(equity); maximumDrawdown = Math.max(maximumDrawdown, drawdown); }
  return { median: quantile(ending, 0.5), p05: quantile(ending, 0.05), p95: quantile(ending, 0.95), maximum_drawdown: maximumDrawdown, ending_equity: ending, simulations, seed };
}

export function bootstrapMetrics(trades: readonly AnalysisTrade[], samples = 10_000, seed = 20250713): BootstrapSummary {
  if (!trades.length) return { samples, seed, confidence_level: 0.95, expectancy: [0, 0], profit_factor: [0, 0], win_rate: [0, 0], average_return: [0, 0] };
  const random = rng(seed); const expectancy: number[] = []; const profitFactor: number[] = []; const winRate: number[] = []; const averageReturn: number[] = [];
  for (let sample = 0; sample < samples; sample += 1) { const selected = Array.from({ length: trades.length }, () => trades[Math.floor(random() * trades.length)]); const metrics = summarizeTrades(selected); expectancy.push(metrics.expectancy); profitFactor.push(metrics.profit_factor === Infinity ? Number.MAX_SAFE_INTEGER : metrics.profit_factor); winRate.push(metrics.win_rate); averageReturn.push(mean(selected.map((trade) => trade.return_percent))); }
  return { samples, seed, confidence_level: 0.95, expectancy: [quantile(expectancy, 0.025), quantile(expectancy, 0.975)], profit_factor: [quantile(profitFactor, 0.025), quantile(profitFactor, 0.975)], win_rate: [quantile(winRate, 0.025), quantile(winRate, 0.975)], average_return: [quantile(averageReturn, 0.025), quantile(averageReturn, 0.975)] };
}

export function riskOfRuin(trades: readonly AnalysisTrade[], simulations = 10_000, seed = 20250713, capital = 100_000): RiskOfRuinSummary {
  const random = rng(seed); let ruin = 0; let dd20 = 0; let dd30 = 0; let doubled = 0; let newHigh = 0;
  for (let simulation = 0; simulation < simulations; simulation += 1) { let equity = capital; let peak = capital; let maxDd = 0; let high = false; for (const trade of shuffled(trades, random)) { equity += trade.net_pnl; if (equity > peak) { peak = equity; high = true; } maxDd = Math.max(maxDd, (peak - equity) / peak); } if (equity <= 0) ruin += 1; if (maxDd >= 0.2) dd20 += 1; if (maxDd >= 0.3) dd30 += 1; if (equity >= capital * 2) doubled += 1; if (high) newHigh += 1; }
  return { risk_of_ruin: ruin / simulations, probability_drawdown_20: dd20 / simulations, probability_drawdown_30: dd30 / simulations, probability_equity_doubling: doubled / simulations, probability_new_equity_high: newHigh / simulations, simulations };
}

function regimeName(trade: AnalysisTrade): string { const value = trade.market_regime.toLowerCase(); if (value.includes("trend up") || value.includes("bull")) return "Bull / Trending"; if (value.includes("trend down") || value.includes("bear")) return "Bear / Trending"; if (value.includes("range") || value.includes("chop") || value.includes("sideways")) return "Sideways / Mean reverting"; return trade.market_regime; }
function grouped(trades: readonly AnalysisTrade[], dimension: string, keyFor: (trade: AnalysisTrade) => string): RegimeSummary[] { const groups = new Map<string, AnalysisTrade[]>(); for (const trade of trades) { const key = keyFor(trade); groups.set(key, [...(groups.get(key) ?? []), trade]); } return [...groups.entries()].map(([key, group]) => { const metrics = summarizeTrades(group); return { dimension, key, trade_count: group.length, net_profit: metrics.net_profit, win_rate: metrics.win_rate, expectancy: metrics.expectancy, profit_factor: metrics.profit_factor }; }); }

function volatilityBand(trade: AnalysisTrade): string { const value = Number(trade.volatility_regime); if (!Number.isFinite(value)) return trade.volatility_regime; if (value >= 0.5) return "High volatility"; if (value <= 0.25) return "Low volatility"; return "Normal volatility"; }
export function regimeAnalysis(trades: readonly AnalysisTrade[]): RegimeSummary[] { return [...grouped(trades, "dataset", (trade) => trade.data_snapshot_id), ...grouped(trades, "symbol", (trade) => trade.instrument), ...grouped(trades, "market_regime", regimeName), ...grouped(trades, "volatility", volatilityBand), ...grouped(trades, "trend_type", (trade) => regimeName(trade).includes("Trending") ? "Trending" : "Mean reverting")]; }
export function walkForward(trades: readonly AnalysisTrade[], window = 10): WalkForwardRow[] { const ordered = [...trades].sort((a, b) => Date.parse(a.exit_timestamp_utc) - Date.parse(b.exit_timestamp_utc)); const rows: WalkForwardRow[] = []; for (let index = window; index <= ordered.length; index += 1) { const group = ordered.slice(index - window, index); const metrics = summarizeTrades(group); rows.push({ start: group[0].entry_timestamp_utc, end: group.at(-1)!.exit_timestamp_utc, trade_count: group.length, expectancy: metrics.expectancy, sharpe: metrics.sharpe_ratio, drawdown: metrics.maximum_drawdown }); } return rows; }

export function buildStatisticalReport(input: { replayIds: string[]; trades: readonly AnalysisTrade[]; datasets: unknown[]; capital?: number; generatedAt?: string }): StatisticalAnalysisReport {
  const capital = input.capital ?? 100_000; const metrics = summarizeTrades(input.trades, capital); const ordered = [...input.trades].sort((a, b) => Date.parse(a.exit_timestamp_utc) - Date.parse(b.exit_timestamp_utc)); const split = Math.floor(ordered.length / 3) || ordered.length; const training = ordered.slice(0, split); const validation = ordered.slice(split, split * 2); const outOfSample = ordered.slice(split * 2); const limitations = input.trades.length < 30 ? ["Fewer than 30 completed trades: confidence intervals and regime conclusions are exploratory, not statistically reliable."] : [];
  const concentration = metrics.net_profit !== 0 ? metrics.largest_win / metrics.net_profit : 0; const datasetGroups = grouped(input.trades, "dataset", (trade) => trade.data_snapshot_id); const dependency = datasetGroups.length <= 1;
  return { schema_version: "1.0", generated_at: input.generatedAt ?? new Date().toISOString(), replay_ids: input.replayIds, capital, executive_summary: `${metrics.trade_count} completed trades produced ${metrics.net_profit.toFixed(2)} net profit with ${(metrics.win_rate * 100).toFixed(2)}% win rate.`, dataset_summary: input.datasets, trade_statistics: metrics, monte_carlo: monteCarlo(input.trades, 10_000, 20250713, capital), bootstrap: bootstrapMetrics(input.trades, 10_000, 20250713), risk_of_ruin: riskOfRuin(input.trades, 10_000, 20250713, capital), regime_analysis: regimeAnalysis(input.trades), out_of_sample: { training: summarizeTrades(training, capital), validation: summarizeTrades(validation, capital), out_of_sample: summarizeTrades(outOfSample, capital) }, walk_forward: walkForward(input.trades), robustness: { performance_concentration_largest_win_share: concentration, single_trade_dependency: concentration > 0.5, dataset_dependency: dependency, dataset_count: datasetGroups.length, regime_dependency: regimeAnalysis(input.trades).filter((row) => row.dimension === "market_regime").length < 2 }, known_limitations: limitations, conclusion: input.trades.length < 30 ? "INSUFFICIENT EVIDENCE: the observed result is not yet statistically defensible because the completed-trade sample is small." : metrics.expectancy > 0 ? "PRELIMINARY POSITIVE EVIDENCE: validate across additional independent datasets before claiming a production edge." : "NO POSITIVE EDGE DETECTED IN THE ANALYZED ARTIFACTS." };
}

export function renderStatisticalReport(report: StatisticalAnalysisReport): string { const m = report.trade_statistics; const mc = report.monte_carlo; const b = report.bootstrap; const r = report.risk_of_ruin; return ["# Statistical Edge Validation Report", "", "## Executive Summary", report.executive_summary, `Conclusion: **${report.conclusion}**`, "", "## Dataset Summary", `Replay artifacts: ${report.replay_ids.length}`, `Datasets: ${report.dataset_summary.length}`, "", "## Trade Statistics", `Trades: ${m.trade_count}`, `Wins / losses: ${m.winning_trades} / ${m.losing_trades}`, `Win rate: ${(m.win_rate * 100).toFixed(2)}%`, `Average win / loss: ${m.average_win.toFixed(2)} / ${m.average_loss.toFixed(2)}`, `Net profit: ${m.net_profit.toFixed(2)}`, `Expectancy: ${m.expectancy.toFixed(2)}`, `Profit factor: ${m.profit_factor.toFixed(4)}`, `Average R: ${m.average_r_multiple.toFixed(4)}`, "", "## Risk Metrics", `Maximum drawdown: ${(m.maximum_drawdown * 100).toFixed(2)}%`, `Maximum equity drawdown: ${m.maximum_equity_drawdown.toFixed(2)}`, `Time under water: ${(m.time_under_water * 100).toFixed(2)}%`, "", "## Portfolio Metrics", `CAGR: ${m.cagr === null ? "not available" : `${(m.cagr * 100).toFixed(2)}%`}`, `Sharpe: ${m.sharpe_ratio === null ? "not available" : m.sharpe_ratio.toFixed(4)}`, `Sortino: ${m.sortino_ratio === null ? "not available" : m.sortino_ratio.toFixed(4)}`, "", "## Monte Carlo", `Simulations: ${mc.simulations}`, `Median ending equity: ${mc.median.toFixed(2)}`, `Worst 5% ending equity: ${mc.p05.toFixed(2)}`, `Best 5% ending equity: ${mc.p95.toFixed(2)}`, `Maximum simulated drawdown: ${(mc.maximum_drawdown * 100).toFixed(2)}%`, "", "## Bootstrap 95% Confidence Intervals", `Expectancy: ${b.expectancy[0].toFixed(2)} to ${b.expectancy[1].toFixed(2)}`, `Profit factor: ${b.profit_factor[0].toFixed(4)} to ${b.profit_factor[1].toFixed(4)}`, `Win rate: ${(b.win_rate[0] * 100).toFixed(2)}% to ${(b.win_rate[1] * 100).toFixed(2)}%`, `Average return: ${(b.average_return[0] * 100).toFixed(2)}% to ${(b.average_return[1] * 100).toFixed(2)}%`, "", "## Risk Of Ruin", `Risk of ruin: ${(r.risk_of_ruin * 100).toFixed(2)}%`, `Probability of 20% drawdown: ${(r.probability_drawdown_20 * 100).toFixed(2)}%`, `Probability of 30% drawdown: ${(r.probability_drawdown_30 * 100).toFixed(2)}%`, `Probability of doubling: ${(r.probability_equity_doubling * 100).toFixed(2)}%`, `Probability of new equity high: ${(r.probability_new_equity_high * 100).toFixed(2)}%`, "", "## Regime Analysis", ...report.regime_analysis.map((row) => `${row.dimension} / ${row.key}: ${row.trade_count} trades, net ${row.net_profit.toFixed(2)}, expectancy ${row.expectancy.toFixed(2)}`), "", "## Robustness Assessment", ...Object.entries(report.robustness).map(([key, value]) => `${key}: ${value}`), "", "## Known Limitations", ...(report.known_limitations.length ? report.known_limitations.map((value) => `- ${value}`) : ["- None recorded"]), ""].join("\n"); }
